# GitHub Release Notes Configuration
# Automatically generates release notes from merged PRs
# See: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-changelog
      - internal
      - bot
    authors:
      - dependabot
      - dependabot[bot]
      - github-actions[bot]
  categories:
    - title: "Features"
      labels:
        - feature
        - enhancement
    - title: "Bug Fixes"
      labels:
        - bug
        - fix
    - title: "Breaking Changes"
      labels:
        - breaking
    - title: "Dependencies"
      labels:
        - dependencies
    - title: "Other Changes"
      labels:
        - "*"
