# GitGuardian Configuration
# https://docs.gitguardian.com/ggshield-docs/reference/gitguardian-yaml

version: 2

secret:
  # Ignore files containing default development passwords
  # These are well-known defaults for local PostgreSQL testing, not real secrets
  ignored_paths:
    - tests/**
    - "**/*.test.js"
    - "**/*.spec.js"
    - "**/*.bench.js"
    - src/sync.js
    - src/pg-wire.js
    - src/postgres.js
    - src/restore.js

  # Ignore "postgres" as a password - this is a well-known default for local dev
  ignored_matches:
    - name: "Default postgres password"
      match: postgres

  # Ignore generic password detector (too many false positives for default creds)
  ignored_detectors:
    - Generic Password
    - Generic High Entropy Secret
